POST http://localhost:3001/api/auth/register HTTP/1.1
Content-Type: application/json

{
"email": "correocontra@gmail.com",
"password": "testcontra"
}

###
POST http://localhost:3001/api/auth/validation
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFhNmRhMGE2Mzk0MDFmYTQ0NzkzY2UiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2NTYyNDY0LCJleHAiOjE3NDY2NDg4NjR9.stbkYjJxRqivY7eInC0VlCYflciiGWmcP8C9Pczy8QM
Content-Type: application/json

{
    "code": "606699"
}

###
PATCH http://localhost:3001/api/auth/password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFhNzQyY2U4NGVjMmE3YWQyY2FjMjkiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2NTY0MTQxLCJleHAiOjE3NDY2NTA1NDF9.nzwJYXHYbdRN0t_fGjKwBfktrcuD7BUu47YkjrSkK9U
Content-Type: application/json

{
    "currentPassword": "testcontra",
    "newPassword": "miNuevaContraseña456"
}

###
POST http://localhost:3001/api/auth/login HTTP/1.1
Content-Type: application/json

{
"email": "correo@gmail.com",
"password": "testcontra"
}
###
PUT http://localhost:3001/api/auth/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U1ODZmNjUxNmRkNzRlODJjYzAwMmQiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzMDk1NTQyLCJleHAiOjE3NDMxMDI3NDJ9.fWjUVDTcsR8CdtsPPS7xf1YX_Mgk7Y--AxsbgdEmGKM
Content-Type: application/json

{
  "name": "Sara",
  "surnames": "Garcia Medina",
  "nif": "12345678S"
}

###
PATCH http://localhost:3001/api/auth/company
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U2NzJkZWE5ZjVmYmEwYTM4ZDk1NTQiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzMTU1OTM0LCJleHAiOjE3NDMxNjMxMzR9.1S0DBCAjKLkqoeM7Kp3x88gIctEEugiYl6yN1rA2Nvg
Content-Type: application/json

{
  "company": {
    "name": "cresher L.C.",
    "cif": "11112023L",
    "street": "calle",
    "number": 3,
    "postal": 11112,
    "city": "La madre",
    "province": "Tenerife"
  }
}

###
POST http://localhost:3001/api/auth/logo HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U2NzJkZWE5ZjVmYmEwYTM4ZDk1NTQiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzMTU1OTM0LCJleHAiOjE3NDMxNjMxMzR9.1S0DBCAjKLkqoeM7Kp3x88gIctEEugiYl6yN1rA2Nvg
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="image"; filename="logo.jpg"
Content-Type: image/jpeg

< ./logo.jpg
--boundary123--

###
GET http://localhost:3001/api/auth/profile 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U2NzJkZWE5ZjVmYmEwYTM4ZDk1NTQiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzMTU1OTM0LCJleHAiOjE3NDMxNjMxMzR9.1S0DBCAjKLkqoeM7Kp3x88gIctEEugiYl6yN1rA2Nvg


###
DELETE http://localhost:3001/api/auth/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U1YjA4ZTU5ODQ3NjE4MWFlNDI4MzMiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzMTA2MTkwLCJleHAiOjE3NDMxMTMzOTB9.o8gzg7FW34XI6WT6qn4uLLac-ssCKR7GRotaGKqhgVo


###
POST http://localhost:3001/api/client
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFhMGNjZTU4MWUxYTQyNWM3Njc2MjIiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2NTM3Njc4LCJleHAiOjE3NDY2MjQwNzh9.TswPhzwb5jmn80CtlKobg-VXBiS2ucZcIsLyOyhaUPI
Content-Type: application/json

{
  "name": "cliente segundo user",
  "cif": "D52921210",
  "address": {
    "street": "Carlos V",
    "number": 22,
    "postal": 28936,
    "city": "Móstoles",
    "province": "Madrid"
  }
}

###
PUT http://localhost:3001/api/client/6819e12fd0ef673ae149ff29
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODE5ZTA3M2QwZWY2NzNhZTE0OWZmMjQiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2NTI2MzIzLCJleHAiOjE3NDY1MzM1MjN9.iSTqEqJcCKyi_Z_STuFbYUYA8CtxzupXEsME5Q4v4V4
Content-Type: application/json

{
  "name": "ACS Actualizado",
  "cif": "D52921210",
  "address": {
    "street": "Carlos V",
    "number": 30,
    "postal": 28936,
    "city": "Móstoles",
    "province": "Madrid"
  }
}

###
GET http://localhost:3001/api/client
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFhMGNjZTU4MWUxYTQyNWM3Njc2MjIiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2NTM3Njc4LCJleHAiOjE3NDY2MjQwNzh9.TswPhzwb5jmn80CtlKobg-VXBiS2ucZcIsLyOyhaUPI

###
GET http://localhost:3001/api/client/6819e5533464e12a69025c83
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODE5ZTA3M2QwZWY2NzNhZTE0OWZmMjQiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2NTI2MzIzLCJleHAiOjE3NDY1MzM1MjN9.iSTqEqJcCKyi_Z_STuFbYUYA8CtxzupXEsME5Q4v4V4

###
DELETE http://localhost:3001/api/client/soft/6819ecb0726b289e6f469aee
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODE5ZTA3M2QwZWY2NzNhZTE0OWZmMjQiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2NTI2MzIzLCJleHAiOjE3NDY1MzM1MjN9.iSTqEqJcCKyi_Z_STuFbYUYA8CtxzupXEsME5Q4v4V4

###
DELETE http://localhost:3001/api/client/6819e5533464e12a69025c83
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODE5ZTA3M2QwZWY2NzNhZTE0OWZmMjQiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2NTI2MzIzLCJleHAiOjE3NDY1MzM1MjN9.iSTqEqJcCKyi_Z_STuFbYUYA8CtxzupXEsME5Q4v4V4

###
GET http://localhost:3001/api/client/archived
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODE5ZTA3M2QwZWY2NzNhZTE0OWZmMjQiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2NTI2MzIzLCJleHAiOjE3NDY1MzM1MjN9.iSTqEqJcCKyi_Z_STuFbYUYA8CtxzupXEsME5Q4v4V4

###
PATCH http://localhost:3001/api/client/restore/6819ecb0726b289e6f469aee
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODE5ZTA3M2QwZWY2NzNhZTE0OWZmMjQiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2NTI2MzIzLCJleHAiOjE3NDY1MzM1MjN9.iSTqEqJcCKyi_Z_STuFbYUYA8CtxzupXEsME5Q4v4V4


###
POST http://localhost:3001/api/project HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFhMGNjZTU4MWUxYTQyNWM3Njc2MjIiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2NTM3Njc4LCJleHAiOjE3NDY2MjQwNzh9.TswPhzwb5jmn80CtlKobg-VXBiS2ucZcIsLyOyhaUPI
Content-Type: application/json

{
  "name": "proyecto segundo user",
  "projectCode": "0002",
  "email": "mimail@gmail.com",
  "address": {
    "street": "Carlos V",
    "number": 22,
    "postal": 28936,
    "city": "Móstoles",
    "province": "Madrid"
  },
  "code": "Código interno del proyecto",
  "clientId": "681a0fdf04ecc869dbd912e4"
}


###
PUT http://localhost:3001/api/project/681a0ce8581e1a425c767627
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFhMGNjZTU4MWUxYTQyNWM3Njc2MjIiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2NTM3Njc4LCJleHAiOjE3NDY2MjQwNzh9.TswPhzwb5jmn80CtlKobg-VXBiS2ucZcIsLyOyhaUPI
Content-Type: application/json

{
  "name": "Proyecto actualizado",
  "email": "nuevoemail@correo.com",
  "address": {
    "street": "Calle Nueva",
    "number": 123,
    "postal": 28080,
    "city": "Madrid",
    "province": "Madrid"
  },
  "code": "NUEVO123",
  "projectCode": "NEW456"
}

###
GET http://localhost:3001/api/project
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFhMGNjZTU4MWUxYTQyNWM3Njc2MjIiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2NTM3Njc4LCJleHAiOjE3NDY2MjQwNzh9.TswPhzwb5jmn80CtlKobg-VXBiS2ucZcIsLyOyhaUPI


###
GET http://localhost:3001/api/project/681a102104ecc869dbd912e9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFhMGNjZTU4MWUxYTQyNWM3Njc2MjIiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2NTM3Njc4LCJleHAiOjE3NDY2MjQwNzh9.TswPhzwb5jmn80CtlKobg-VXBiS2ucZcIsLyOyhaUPI

###
DELETE http://localhost:3001/api/project/soft/681a0ce8581e1a425c767627
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFhMGNjZTU4MWUxYTQyNWM3Njc2MjIiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2NTM3Njc4LCJleHAiOjE3NDY2MjQwNzh9.TswPhzwb5jmn80CtlKobg-VXBiS2ucZcIsLyOyhaUPI

###
DELETE http://localhost:3001/api/project/681a0ce8581e1a425c767627
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFhMGNjZTU4MWUxYTQyNWM3Njc2MjIiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2NTM3Njc4LCJleHAiOjE3NDY2MjQwNzh9.TswPhzwb5jmn80CtlKobg-VXBiS2ucZcIsLyOyhaUPI


###
PATCH http://localhost:3001/api/project/restore/681a0ce8581e1a425c767627
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFhMGNjZTU4MWUxYTQyNWM3Njc2MjIiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2NTM3Njc4LCJleHAiOjE3NDY2MjQwNzh9.TswPhzwb5jmn80CtlKobg-VXBiS2ucZcIsLyOyhaUPI


###
POST http://localhost:3001/api/deliverynote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFhMGNjZTU4MWUxYTQyNWM3Njc2MjIiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2NTM3Njc4LCJleHAiOjE3NDY2MjQwNzh9.TswPhzwb5jmn80CtlKobg-VXBiS2ucZcIsLyOyhaUPI
Content-Type: application/json

{
  "clientId": "681a0fdf04ecc869dbd912e4",
  "projectId": "681a102104ecc869dbd912e9",
  "format": "material",
  "material": "Hormigón armado",
  "description": "Material utilizado en cimentación",
  "workdate": "2024-06-02"
}

###
GET http://localhost:3001/api/deliverynote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFhMGNjZTU4MWUxYTQyNWM3Njc2MjIiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2NTM3Njc4LCJleHAiOjE3NDY2MjQwNzh9.TswPhzwb5jmn80CtlKobg-VXBiS2ucZcIsLyOyhaUPI

###
GET http://localhost:3001/api/deliverynote/681a2451a0f8f666bff4927d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFhMGNjZTU4MWUxYTQyNWM3Njc2MjIiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2NTM3Njc4LCJleHAiOjE3NDY2MjQwNzh9.TswPhzwb5jmn80CtlKobg-VXBiS2ucZcIsLyOyhaUPI

###
curl -X GET http://localhost:3001/api/deliverynote/pdf/681a2451a0f8f666bff4927d 
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFhMGNjZTU4MWUxYTQyNWM3Njc2MjIiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ2NTM3Njc4LCJleHAiOjE3NDY2MjQwNzh9.TswPhzwb5jmn80CtlKobg-VXBiS2ucZcIsLyOyhaUPI" 
  --output albaran.pdf